### ISSUE TITLE
Question about rotation axis

### ISSUE THREAD

**Issue by LemonQC** [gao-xiao-bai/Rotate3D#1]
![image](https://user-images.githubusercontent.com/30914380/108480433-e9224280-72d1-11eb-9612-f67298aa6d89.png)
Why the equation can be used for obtaining rotation axis

**Comment by gao-xiao-bai** [comment]
As mentioned in the paper, the rotation axis u is a three-dimensional unit vector.  These equations can guarantee that u is a unit vector.

**Comment by LemonQC** [comment]
Ohh,Thanks, and what‘s your experimental requirements, Nvidia 2080TI or higher, I run out of memory

**Comment by gao-xiao-bai** [comment]
I use Tesla V100.
